/**
 * Hyphenate REST APIs
 * Hyphenate Server REST API Swagger is designated to provide better documentation and thorough interfaces for testing. For more details about server implementation, request rate limitation, etc, please visit [Hyphenate Server Integration](http://docs.hyphenate.io/v1.0/docs/server-overview).    **Note:**  `org_ID` is the unique ID of the organization created when you first registered [Hyphenate console](https://console.hyphenate.io/).                          `app_name` is the unique app ID created when you new application in [Hyphenate console](https://console.hyphenate.io/).            `Authorization token` is required for most API requests as part of requesting header in the format `Bearer ${token}`. You can obtain the token via [/{org_name}/{app_name}/token](https://docs.hyphenate.io/docs/server-overview#section-request-authentication-token).                                             
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HyphenateRestApIs) {
      root.HyphenateRestApIs = {};
    }
    root.HyphenateRestApIs.ChatHistoryApi = factory(root.HyphenateRestApIs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * ChatHistory service.
   * @module api/ChatHistoryApi
   * @version 1.0.2
   */

  /**
   * Constructs a new ChatHistoryApi. 
   * @alias module:api/ChatHistoryApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the orgNameAppNameChatmessagesGet operation.
     * @callback module:api/ChatHistoryApi~orgNameAppNameChatmessagesGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Message History
     * 
     * @param {String} orgName Organization ID
     * @param {String} appName Application name
     * @param {String} authorization Bearer ${token}
     * @param {Object} opts Optional parameters
     * @param {String} opts.ql Get messages based on starting  timestamp. Could also alter the comparison to get later, equal, or earlier messages. ex. ql&#x3D;select+*+where+timestamp&gt;1403164734226 or &#x3D;&lt;[timestamp] (default to select+*+where+timestamp&gt;1403164734226)
     * @param {String} opts.limit total number of messages per page by pagination at a time (default to 3)
     * @param {String} opts.cursor Get messages by pagination. Obtained \&quot;cursor\&quot; from the previous GET messages call response. (default to )
     * @param {module:api/ChatHistoryApi~orgNameAppNameChatmessagesGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.orgNameAppNameChatmessagesGet = function(orgName, appName, authorization, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'orgName' is set
      if (orgName == undefined || orgName == null) {
        throw "Missing the required parameter 'orgName' when calling orgNameAppNameChatmessagesGet";
      }

      // verify the required parameter 'appName' is set
      if (appName == undefined || appName == null) {
        throw "Missing the required parameter 'appName' when calling orgNameAppNameChatmessagesGet";
      }

      // verify the required parameter 'authorization' is set
      if (authorization == undefined || authorization == null) {
        throw "Missing the required parameter 'authorization' when calling orgNameAppNameChatmessagesGet";
      }


      var pathParams = {
        'org_name': orgName,
        'app_name': appName
      };
      var queryParams = {
        'ql': opts['ql'],
        'limit': opts['limit'],
        'cursor': opts['cursor']
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{org_name}/{app_name}/chatmessages', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
