/**
 * Hyphenate REST APIs
 * Hyphenate Server REST API Swagger is designated to provide better documentation and thorough interfaces for testing. For more details about server implementation, request rate limitation, etc, please visit [Hyphenate Server Integration](http://docs.hyphenate.io/v1.0/docs/server-overview).    **Note:**  `org_ID` is the unique ID of the organization created when you first registered [Hyphenate console](https://console.hyphenate.io/).                          `app_name` is the unique app ID created when you new application in [Hyphenate console](https://console.hyphenate.io/).            `Authorization token` is required for most API requests as part of requesting header in the format `Bearer ${token}`. You can obtain the token via [/{org_name}/{app_name}/token](https://docs.hyphenate.io/docs/server-overview#section-request-authentication-token).                                             
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HyphenateRestApIs) {
      root.HyphenateRestApIs = {};
    }
    root.HyphenateRestApIs.UploadAndDownloadFilesApi = factory(root.HyphenateRestApIs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * UploadAndDownloadFiles service.
   * @module api/UploadAndDownloadFilesApi
   * @version 1.0.2
   */

  /**
   * Constructs a new UploadAndDownloadFilesApi. 
   * @alias module:api/UploadAndDownloadFilesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the orgNameAppNameChatfilesPost operation.
     * @callback module:api/UploadAndDownloadFilesApi~orgNameAppNameChatfilesPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Upload a File
     * Warning: File cannot be over 10MB, otherwise will fail. Important: Be sure keep the \&quot;uuid\&quot; and \&quot;share-secret\&quot;, which are requirement when downloading particular file.
     * @param {String} orgName Organization ID
     * @param {String} appName Application name
     * @param {String} authorization Bearer ${token}
     * @param {File} file 
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.restrictAccess \&quot;restrict-access\&quot; determines whether later the file require \&quot;share-secret\&quot; for access or allow public access.  (default to )
     * @param {module:api/UploadAndDownloadFilesApi~orgNameAppNameChatfilesPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.orgNameAppNameChatfilesPost = function(orgName, appName, authorization, file, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'orgName' is set
      if (orgName == undefined || orgName == null) {
        throw "Missing the required parameter 'orgName' when calling orgNameAppNameChatfilesPost";
      }

      // verify the required parameter 'appName' is set
      if (appName == undefined || appName == null) {
        throw "Missing the required parameter 'appName' when calling orgNameAppNameChatfilesPost";
      }

      // verify the required parameter 'authorization' is set
      if (authorization == undefined || authorization == null) {
        throw "Missing the required parameter 'authorization' when calling orgNameAppNameChatfilesPost";
      }

      // verify the required parameter 'file' is set
      if (file == undefined || file == null) {
        throw "Missing the required parameter 'file' when calling orgNameAppNameChatfilesPost";
      }


      var pathParams = {
        'org_name': orgName,
        'app_name': appName
      };
      var queryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'restrict-access': opts['restrictAccess']
      };
      var formParams = {
        'file': file
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{org_name}/{app_name}/chatfiles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orgNameAppNameChatfilesUuidGet operation.
     * @callback module:api/UploadAndDownloadFilesApi~orgNameAppNameChatfilesUuidGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download a File
     * Important: 1. Include the share-secret from HTTP header  2. Include uuid from the response of a successful file uploading, which is the file identifier 
     * @param {String} orgName Organization ID
     * @param {String} appName Application name
     * @param {String} authorization Bearer ${token}
     * @param {String} uuid uuid, the file identifier, from previous successful uploading reponse
     * @param {String} shareSecret share-secret from previous successful uploading response
     * @param {Boolean} thumbnail The request will return thumbnail if the tag of “thumbnail: true” is explicitly put in the header
     * @param {module:api/UploadAndDownloadFilesApi~orgNameAppNameChatfilesUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.orgNameAppNameChatfilesUuidGet = function(orgName, appName, authorization, uuid, shareSecret, thumbnail, callback) {
      var postBody = null;

      // verify the required parameter 'orgName' is set
      if (orgName == undefined || orgName == null) {
        throw "Missing the required parameter 'orgName' when calling orgNameAppNameChatfilesUuidGet";
      }

      // verify the required parameter 'appName' is set
      if (appName == undefined || appName == null) {
        throw "Missing the required parameter 'appName' when calling orgNameAppNameChatfilesUuidGet";
      }

      // verify the required parameter 'authorization' is set
      if (authorization == undefined || authorization == null) {
        throw "Missing the required parameter 'authorization' when calling orgNameAppNameChatfilesUuidGet";
      }

      // verify the required parameter 'uuid' is set
      if (uuid == undefined || uuid == null) {
        throw "Missing the required parameter 'uuid' when calling orgNameAppNameChatfilesUuidGet";
      }

      // verify the required parameter 'shareSecret' is set
      if (shareSecret == undefined || shareSecret == null) {
        throw "Missing the required parameter 'shareSecret' when calling orgNameAppNameChatfilesUuidGet";
      }

      // verify the required parameter 'thumbnail' is set
      if (thumbnail == undefined || thumbnail == null) {
        throw "Missing the required parameter 'thumbnail' when calling orgNameAppNameChatfilesUuidGet";
      }


      var pathParams = {
        'org_name': orgName,
        'app_name': appName,
        'uuid': uuid
      };
      var queryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'share-secret': shareSecret,
        'thumbnail': thumbnail
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{org_name}/{app_name}/chatfiles/{uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
